version: 0.2
    
env:
   variables:
     PROJECT: Dotnet6Web
     DOTNET_CORE_RUNTIME: 6.0

phases:   
  install:
    commands:
    - /usr/local/bin/dotnet-install.sh --channel LTS
    #runtime-versions:
    #  dotnet: ${DOTNET_CORE_RUNTIME}
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore Dotnet6Test.sln
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build -c Release
      #- dotnet test -c Release --logger trx --results-directory ./testresults
      
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release  -r linux-x64 -o ./build_output ./${PROJECT}/Dotnet6.Web.csproj --self-contained false
      - cp ./appspec.yml ./build_output
      - cp ./installApp.sh ./build_output

artifacts:
  files:
    - '**/*'
  base-directory: ./build_output
  discard-paths: no

#reports:
#  ${PROJECT}:
#    file-format: VisualStudioTrx
#    files:
#      - '**/*'
#    base-directory: './testresults'
